/**
 * 약 이름 별칭 — 영어 제네릭명 외 한국어 등으로 입력해도 인식되도록.
 * key = meds.ts의 영어 제네릭명, value = 동일 약의 대체 이름 목록 (주로 한국어).
 */
export const MED_ALIASES: Record<string, string[]> = {
  // ── 통증·염증·면역 ──
  'acetaminophen': ['아세트아미노펜'],
  'paracetamol': ['파라세타몰', '아세트아미노펜'],
  'ibuprofen': ['이부프로펜'],
  'naproxen': ['나프록센'],
  'diclofenac': ['디클로페낙'],
  'meloxicam': ['멜록시캄'],
  'aspirin': ['아스피린'],
  'celecoxib': ['셀레콕시브'],
  'tramadol': ['트라마돌'],
  'codeine': ['코데인'],
  'prednisone': ['프레드니손'],
  'prednisolone': ['프레드니솔론'],
  'methylprednisolone': ['메틸프레드니솔론'],
  'dexamethasone': ['덱사메타손'],
  'hydrocortisone': ['하이드로코르티손'],
  'methotrexate': ['메토트렉세이트'],
  'hydroxychloroquine': ['하이드록시클로로퀸'],
  'sulfasalazine': ['설파살라진'],
  'azathioprine': ['아자티오프린'],
  'mycophenolate': ['마이코페놀레이트'],
  'adalimumab': ['아달리무맙'],
  'infliximab': ['인플릭시맙'],
  'tocilizumab': ['토실리주맙'],
  'rituximab': ['리툭시맙'],
  'colchicine': ['콜히친'],
  // ── 위장관 ──
  'omeprazole': ['오메프라졸'],
  'esomeprazole': ['에스오메프라졸'],
  'pantoprazole': ['판토프라졸'],
  'lansoprazole': ['란소프라졸'],
  'famotidine': ['파모티딘'],
  'metoclopramide': ['메토클로프라미드'],
  'ondansetron': ['온단세트론'],
  'loperamide': ['로페라미드'],
  'bismuth': ['비스무트'],
  'mesalamine': ['메살라진'],
  'budesonide': ['부데소니드'],
  'dicyclomine': ['디시클로민'],
  'polyethylene': ['폴리에틸렌글리콜'],
  'lactulose': ['락툴로스'],
  'senna': ['센나'],
  'psyllium': ['실리움'],
  // ── 대사 ──
  'metformin': ['메트포르민'],
  'glipizide': ['글리피지드'],
  'empagliflozin': ['엠파글리플로진'],
  'liraglutide': ['리라글루타이드'],
  'semaglutide': ['세마글루타이드'],
  'insulin': ['인슐린'],
  'levothyroxine': ['레보티록신'],
  'allopurinol': ['알로푸리놀'],
  'febuxostat': ['페북소스타트'],
  // ── 심혈관 ──
  'atorvastatin': ['아토르바스타틴'],
  'rosuvastatin': ['로수바스타틴'],
  'simvastatin': ['심바스타틴'],
  'amlodipine': ['암로디핀'],
  'lisinopril': ['리시노프릴'],
  'losartan': ['로사르탄'],
  'metoprolol': ['메토프롤롤'],
  'propranolol': ['프로프라놀롤'],
  'furosemide': ['푸로세미드'],
  'hydrochlorothiazide': ['하이드로클로로티아지드'],
  'spironolactone': ['스피로놀락톤'],
  'warfarin': ['와파린'],
  'apixaban': ['아픽사반'],
  'clopidogrel': ['클로피도그렐'],
  'nitroglycerin': ['니트로글리세린'],
  'digoxin': ['디곡신'],
  // ── 호흡기 ──
  'albuterol': ['알부테롤'],
  'salbutamol': ['살부타몰'],
  'fluticasone': ['플루티카손'],
  'montelukast': ['몬테루카스트'],
  'ipratropium': ['이프라트로피움'],
  'salmeterol': ['살메테롤'],
  // ── 정신·신경 ──
  'sertraline': ['세르트랄린'],
  'fluoxetine': ['플루옥세틴'],
  'escitalopram': ['에스시탈로프람'],
  'venlafaxine': ['벤라팍신'],
  'duloxetine': ['둘록세틴'],
  'amitriptyline': ['아미트립틸린'],
  'gabapentin': ['가바펜틴'],
  'pregabalin': ['프레가발린'],
  'topiramate': ['토피라메이트'],
  'sumatriptan': ['수마트립탄'],
  'levodopa': ['레보도파'],
  'methylphenidate': ['메틸페니데이트'],
  'alprazolam': ['알프라졸람'],
  'zolpidem': ['졸피뎀'],
  'melatonin': ['멜라토닌'],
  // ── 감염 ──
  'amoxicillin': ['아목시실린'],
  'azithromycin': ['아지트로마이신'],
  'ciprofloxacin': ['시프로플록사신'],
  'doxycycline': ['독시사이클린'],
  'fluconazole': ['플루코나졸'],
  'acyclovir': ['아시클로버'],
  'oseltamivir': ['오셀타미비르'],
  // ── 알레르기 ──
  'cetirizine': ['세티리진'],
  'loratadine': ['로라타딘'],
  'fexofenadine': ['펙소페나딘'],
  'diphenhydramine': ['디펜히드라민'],
  'desloratadine': ['데스로라타딘'],
  // 확장 추가
  'bupropion': ['부프로피온'],
  'citalopram': ['시탈로프람'],
  'mirtazapine': ['미르타자핀'],
  'trazodone': ['트라조돈'],
  'carbamazepine': ['카르바마제핀'],
  'lamotrigine': ['라모트리진'],
  'diazepam': ['디아제팜'],
  'lorazepam': ['로라제팜'],
  'carvedilol': ['카르베딜롤'],
  'diltiazem': ['딜티아젬'],
  'valsartan': ['발사르탄'],
  'telmisartan': ['텔미사르탄'],
  'ezetimibe': ['에제티미브'],
  'rivaroxaban': ['리바록사반'],
  'dabigatran': ['다비가트란'],
  'glimepiride': ['글리메피리드'],
  'sitagliptin': ['시타글립틴'],
  'domperidone': ['돔페리돈'],
  'ketorolac': ['케토롤락'],
  'piroxicam': ['피록시캄'],
  'indomethacin': ['인도메타신'],
  'cephalexin': ['세팔렉신'],
  'clarithromycin': ['클라리스로마이신'],
  'metronidazole': ['메트로니다졸'],
  'theophylline': ['테오필린'],
}
