// 약 설명 문장 번역 (1~39) — 키는 영어 원문, 값은 15개 언어 번역 (en은 키 자체)
import type { Localized } from './medsText'

export type InfoTrans = Omit<Localized, 'en'>

export const INFOS_PART1: Record<string, InfoTrans> = {
  'Relieves mild pain and lowers fever.': {
    ja: '軽い痛みを和らげ、熱を下げます。', zh: '缓解轻微疼痛并退烧。', es: 'Alivia el dolor leve y baja la fiebre.', fr: 'Soulage les douleurs légères et fait baisser la fièvre.', de: 'Lindert leichte Schmerzen und senkt Fieber.', pt: 'Alivia a dor leve e baixa a febre.', it: 'Allevia il dolore lieve e abbassa la febbre.', ko: '가벼운 통증을 완화하고 열을 내립니다.', th: 'บรรเทาอาการปวดเล็กน้อยและลดไข้', vi: 'Giảm đau nhẹ và hạ sốt.', id: 'Meredakan nyeri ringan dan menurunkan demam.', tr: 'Hafif ağrıyı giderir ve ateşi düşürür.', ru: 'Снимает лёгкую боль и снижает жар.', ar: 'يخفف الألم الخفيف ويخفض الحمى.', hi: 'हल्के दर्द से राहत देता है और बुखार कम करता है।' },
  'Relieves pain, inflammation, and fever.': {
    ja: '痛み・炎症・熱を和らげます。', zh: '缓解疼痛、炎症和发烧。', es: 'Alivia el dolor, la inflamación y la fiebre.', fr: 'Soulage la douleur, l’inflammation et la fièvre.', de: 'Lindert Schmerzen, Entzündungen und Fieber.', pt: 'Alivia dor, inflamação e febre.', it: 'Allevia dolore, infiammazione e febbre.', ko: '통증·염증·발열을 완화합니다.', th: 'บรรเทาปวด อักเสบ และไข้', vi: 'Giảm đau, viêm và sốt.', id: 'Meredakan nyeri, peradangan, dan demam.', tr: 'Ağrıyı, iltihabı ve ateşi giderir.', ru: 'Снимает боль, воспаление и жар.', ar: 'يخفف الألم والالتهاب والحمى.', hi: 'दर्द, सूजन और बुखार से राहत देता है।' },
  'Relieves pain and inflammation, long-lasting.': {
    ja: '痛みと炎症を長く和らげます。', zh: '长效缓解疼痛和炎症。', es: 'Alivia el dolor y la inflamación de forma duradera.', fr: 'Soulage durablement la douleur et l’inflammation.', de: 'Lindert Schmerzen und Entzündungen langanhaltend.', pt: 'Alivia dor e inflamação por muito tempo.', it: 'Allevia dolore e infiammazione a lungo.', ko: '통증과 염증을 오래 완화합니다.', th: 'บรรเทาปวดและอักเสบได้ยาวนาน', vi: 'Giảm đau và viêm kéo dài.', id: 'Meredakan nyeri dan peradangan tahan lama.', tr: 'Ağrı ve iltihabı uzun süre giderir.', ru: 'Долго снимает боль и воспаление.', ar: 'يخفف الألم والالتهاب لفترة طويلة.', hi: 'लंबे समय तक दर्द और सूजन से राहत देता है।' },
  'Relieves pain and inflammation.': {
    ja: '痛みと炎症を和らげます。', zh: '缓解疼痛和炎症。', es: 'Alivia el dolor y la inflamación.', fr: 'Soulage la douleur et l’inflammation.', de: 'Lindert Schmerzen und Entzündungen.', pt: 'Alivia dor e inflamação.', it: 'Allevia dolore e infiammazione.', ko: '통증과 염증을 완화합니다.', th: 'บรรเทาปวดและอักเสบ', vi: 'Giảm đau và viêm.', id: 'Meredakan nyeri dan peradangan.', tr: 'Ağrıyı ve iltihabı giderir.', ru: 'Снимает боль и воспаление.', ar: 'يخفف الألم والالتهاب.', hi: 'दर्द और सूजन से राहत देता है।' },
  'Relieves arthritis pain and inflammation.': {
    ja: '関節炎の痛みと炎症を和らげます。', zh: '缓解关节炎疼痛和炎症。', es: 'Alivia el dolor y la inflamación de la artritis.', fr: 'Soulage la douleur et l’inflammation de l’arthrite.', de: 'Lindert Schmerzen und Entzündungen bei Arthritis.', pt: 'Alivia dor e inflamação da artrite.', it: 'Allevia dolore e infiammazione dell’artrite.', ko: '관절염의 통증과 염증을 완화합니다.', th: 'บรรเทาปวดและอักเสบจากข้ออักเสบ', vi: 'Giảm đau và viêm khớp.', id: 'Meredakan nyeri dan peradangan radang sendi.', tr: 'Artrit ağrısını ve iltihabını giderir.', ru: 'Снимает боль и воспаление при артрите.', ar: 'يخفف ألم والتهاب المفاصل.', hi: 'गठिया के दर्द और सूजन से राहत देता है।' },
  'Relieves pain and fever; low dose prevents blood clots.': {
    ja: '痛みと熱を和らげ、低用量では血栓を防ぎます。', zh: '缓解疼痛和发烧；低剂量可预防血栓。', es: 'Alivia el dolor y la fiebre; en dosis bajas previene coágulos.', fr: 'Soulage la douleur et la fièvre ; à faible dose, prévient les caillots.', de: 'Lindert Schmerzen und Fieber; niedrig dosiert beugt es Blutgerinnseln vor.', pt: 'Alivia dor e febre; em dose baixa previne coágulos.', it: 'Allevia dolore e febbre; a basse dosi previene i coaguli.', ko: '통증과 발열을 완화하고, 저용량은 혈전을 예방합니다.', th: 'บรรเทาปวดและไข้ ขนาดต่ำป้องกันลิ่มเลือด', vi: 'Giảm đau và sốt; liều thấp ngăn ngừa cục máu đông.', id: 'Meredakan nyeri dan demam; dosis rendah mencegah penggumpalan darah.', tr: 'Ağrı ve ateşi giderir; düşük dozda kan pıhtılarını önler.', ru: 'Снимает боль и жар; в низкой дозе предотвращает тромбы.', ar: 'يخفف الألم والحمى؛ الجرعة المنخفضة تمنع جلطات الدم.', hi: 'दर्द और बुखार से राहत; कम खुराक रक्त के थक्के रोकती है।' },
  'Relieves pain and inflammation with less stomach irritation.': {
    ja: '胃への刺激を抑えながら痛みと炎症を和らげます。', zh: '缓解疼痛和炎症，且较少刺激胃部。', es: 'Alivia el dolor y la inflamación con menos irritación estomacal.', fr: 'Soulage la douleur et l’inflammation avec moins d’irritation de l’estomac.', de: 'Lindert Schmerzen und Entzündungen mit weniger Magenreizung.', pt: 'Alivia dor e inflamação com menos irritação no estômago.', it: 'Allevia dolore e infiammazione con meno irritazione allo stomaco.', ko: '위 자극을 줄이면서 통증과 염증을 완화합니다.', th: 'บรรเทาปวดและอักเสบโดยระคายเคืองกระเพาะน้อยลง', vi: 'Giảm đau và viêm, ít kích ứng dạ dày.', id: 'Meredakan nyeri dan peradangan dengan iritasi lambung lebih sedikit.', tr: 'Mide tahrişini azaltarak ağrı ve iltihabı giderir.', ru: 'Снимает боль и воспаление с меньшим раздражением желудка.', ar: 'يخفف الألم والالتهاب مع تهيج أقل للمعدة.', hi: 'पेट में कम जलन के साथ दर्द और सूजन से राहत।' },
  'Relieves moderate to severe pain.': {
    ja: '中等度から重度の痛みを和らげます。', zh: '缓解中度至重度疼痛。', es: 'Alivia el dolor moderado a intenso.', fr: 'Soulage les douleurs modérées à sévères.', de: 'Lindert mittlere bis starke Schmerzen.', pt: 'Alivia dor moderada a intensa.', it: 'Allevia il dolore da moderato a intenso.', ko: '중등도에서 중증의 통증을 완화합니다.', th: 'บรรเทาอาการปวดระดับปานกลางถึงรุนแรง', vi: 'Giảm đau từ trung bình đến nặng.', id: 'Meredakan nyeri sedang hingga berat.', tr: 'Orta ila şiddetli ağrıyı giderir.', ru: 'Снимает умеренную и сильную боль.', ar: 'يخفف الألم المتوسط إلى الشديد.', hi: 'मध्यम से गंभीर दर्द से राहत देता है।' },
  'Relieves pain and cough.': {
    ja: '痛みと咳を和らげます。', zh: '缓解疼痛和咳嗽。', es: 'Alivia el dolor y la tos.', fr: 'Soulage la douleur et la toux.', de: 'Lindert Schmerzen und Husten.', pt: 'Alivia dor e tosse.', it: 'Allevia dolore e tosse.', ko: '통증과 기침을 완화합니다.', th: 'บรรเทาปวดและไอ', vi: 'Giảm đau và ho.', id: 'Meredakan nyeri dan batuk.', tr: 'Ağrıyı ve öksürüğü giderir.', ru: 'Снимает боль и кашель.', ar: 'يخفف الألم والسعال.', hi: 'दर्द और खांसी से राहत देता है।' },
  'Reduces inflammation and calms immune activity.': {
    ja: '炎症を抑え、免疫の働きを鎮めます。', zh: '减轻炎症并抑制免疫活动。', es: 'Reduce la inflamación y calma la actividad inmune.', fr: 'Réduit l’inflammation et apaise l’activité immunitaire.', de: 'Reduziert Entzündungen und beruhigt die Immunaktivität.', pt: 'Reduz inflamação e acalma a atividade imunológica.', it: 'Riduce l’infiammazione e calma l’attività immunitaria.', ko: '염증을 줄이고 면역 활동을 진정시킵니다.', th: 'ลดการอักเสบและทำให้ภูมิคุ้มกันสงบลง', vi: 'Giảm viêm và làm dịu hoạt động miễn dịch.', id: 'Mengurangi peradangan dan menenangkan aktivitas imun.', tr: 'İltihabı azaltır ve bağışıklık aktivitesini sakinleştirir.', ru: 'Снижает воспаление и успокаивает иммунитет.', ar: 'يقلل الالتهاب ويهدئ نشاط المناعة.', hi: 'सूजन कम करता है और प्रतिरक्षा गतिविधि शांत करता है।' },
  'Reduces inflammation.': {
    ja: '炎症を抑えます。', zh: '减轻炎症。', es: 'Reduce la inflamación.', fr: 'Réduit l’inflammation.', de: 'Reduziert Entzündungen.', pt: 'Reduz a inflamação.', it: 'Riduce l’infiammazione.', ko: '염증을 줄입니다.', th: 'ลดการอักเสบ', vi: 'Giảm viêm.', id: 'Mengurangi peradangan.', tr: 'İltihabı azaltır.', ru: 'Снижает воспаление.', ar: 'يقلل الالتهاب.', hi: 'सूजन कम करता है।' },
  'Reduces inflammation and allergic reactions.': {
    ja: '炎症とアレルギー反応を抑えます。', zh: '减轻炎症和过敏反应。', es: 'Reduce la inflamación y las reacciones alérgicas.', fr: 'Réduit l’inflammation et les réactions allergiques.', de: 'Reduziert Entzündungen und allergische Reaktionen.', pt: 'Reduz inflamação e reações alérgicas.', it: 'Riduce infiammazione e reazioni allergiche.', ko: '염증과 알레르기 반응을 줄입니다.', th: 'ลดการอักเสบและอาการแพ้', vi: 'Giảm viêm và phản ứng dị ứng.', id: 'Mengurangi peradangan dan reaksi alergi.', tr: 'İltihabı ve alerjik reaksiyonları azaltır.', ru: 'Снижает воспаление и аллергические реакции.', ar: 'يقلل الالتهاب وردود الفعل التحسسية.', hi: 'सूजन और एलर्जी प्रतिक्रियाएँ कम करता है।' },
  'Relieves skin irritation and inflammation.': {
    ja: '皮膚のかゆみ・炎症を和らげます。', zh: '缓解皮肤刺激和炎症。', es: 'Alivia la irritación y la inflamación de la piel.', fr: 'Soulage les irritations et inflammations cutanées.', de: 'Lindert Hautreizungen und Entzündungen.', pt: 'Alivia irritação e inflamação da pele.', it: 'Allevia irritazione e infiammazione della pelle.', ko: '피부 자극과 염증을 완화합니다.', th: 'บรรเทาการระคายเคืองและอักเสบของผิวหนัง', vi: 'Giảm kích ứng và viêm da.', id: 'Meredakan iritasi dan peradangan kulit.', tr: 'Cilt tahrişini ve iltihabını giderir.', ru: 'Снимает раздражение и воспаление кожи.', ar: 'يخفف تهيج والتهاب الجلد.', hi: 'त्वचा की जलन और सूजन से राहत देता है।' },
  'Treats autoimmune disease such as rheumatoid arthritis.': {
    ja: '関節リウマチなどの自己免疫疾患を治療します。', zh: '治疗类风湿关节炎等自身免疫性疾病。', es: 'Trata enfermedades autoinmunes como la artritis reumatoide.', fr: 'Traite les maladies auto-immunes comme la polyarthrite rhumatoïde.', de: 'Behandelt Autoimmunerkrankungen wie rheumatoide Arthritis.', pt: 'Trata doenças autoimunes como artrite reumatoide.', it: 'Tratta malattie autoimmuni come l’artrite reumatoide.', ko: '류마티스 관절염 같은 자가면역 질환을 치료합니다.', th: 'รักษาโรคภูมิต้านตนเอง เช่น ข้ออักเสบรูมาตอยด์', vi: 'Điều trị bệnh tự miễn như viêm khớp dạng thấp.', id: 'Mengobati penyakit autoimun seperti artritis reumatoid.', tr: 'Romatoid artrit gibi otoimmün hastalıkları tedavi eder.', ru: 'Лечит аутоиммунные заболевания, такие как ревматоидный артрит.', ar: 'يعالج أمراض المناعة الذاتية مثل التهاب المفاصل الروماتويدي.', hi: 'रूमेटॉइड आर्थराइटिस जैसी ऑटोइम्यून बीमारियों का उपचार करता है।' },
  'Treats lupus and rheumatoid arthritis.': {
    ja: 'ループスと関節リウマチを治療します。', zh: '治疗红斑狼疮和类风湿关节炎。', es: 'Trata el lupus y la artritis reumatoide.', fr: 'Traite le lupus et la polyarthrite rhumatoïde.', de: 'Behandelt Lupus und rheumatoide Arthritis.', pt: 'Trata lúpus e artrite reumatoide.', it: 'Tratta il lupus e l’artrite reumatoide.', ko: '루푸스와 류마티스 관절염을 치료합니다.', th: 'รักษาโรคลูปัสและข้ออักเสบรูมาตอยด์', vi: 'Điều trị lupus và viêm khớp dạng thấp.', id: 'Mengobati lupus dan artritis reumatoid.', tr: 'Lupus ve romatoid artriti tedavi eder.', ru: 'Лечит волчанку и ревматоидный артрит.', ar: 'يعالج الذئبة والتهاب المفاصل الروماتويدي.', hi: 'ल्यूपस और रूमेटॉइड आर्थराइटिस का उपचार करता है।' },
  'Treats inflammatory bowel disease and arthritis.': {
    ja: '炎症性腸疾患と関節炎を治療します。', zh: '治疗炎症性肠病和关节炎。', es: 'Trata la enfermedad inflamatoria intestinal y la artritis.', fr: 'Traite les maladies inflammatoires de l’intestin et l’arthrite.', de: 'Behandelt chronisch-entzündliche Darmerkrankungen und Arthritis.', pt: 'Trata doença inflamatória intestinal e artrite.', it: 'Tratta malattie infiammatorie intestinali e artrite.', ko: '염증성 장질환과 관절염을 치료합니다.', th: 'รักษาโรคลำไส้อักเสบและข้ออักเสบ', vi: 'Điều trị bệnh viêm ruột và viêm khớp.', id: 'Mengobati penyakit radang usus dan artritis.', tr: 'İltihaplı bağırsak hastalığını ve artriti tedavi eder.', ru: 'Лечит воспалительные заболевания кишечника и артрит.', ar: 'يعالج مرض الأمعاء الالتهابي والتهاب المفاصل.', hi: 'सूजन आंत्र रोग और गठिया का उपचार करता है।' },
  'Calms an overactive immune system in autoimmune disease.': {
    ja: '自己免疫疾患の過剰な免疫反応を鎮めます。', zh: '抑制自身免疫性疾病中过度活跃的免疫系统。', es: 'Calma el sistema inmunitario hiperactivo en enfermedades autoinmunes.', fr: 'Apaise un système immunitaire hyperactif dans les maladies auto-immunes.', de: 'Beruhigt ein überaktives Immunsystem bei Autoimmunerkrankungen.', pt: 'Acalma o sistema imunológico hiperativo em doenças autoimunes.', it: 'Calma un sistema immunitario iperattivo nelle malattie autoimmuni.', ko: '자가면역 질환의 과활성 면역계를 진정시킵니다.', th: 'ทำให้ระบบภูมิคุ้มกันที่ทำงานเกินไปสงบในโรคภูมิต้านตนเอง', vi: 'Làm dịu hệ miễn dịch hoạt động quá mức trong bệnh tự miễn.', id: 'Menenangkan sistem imun yang terlalu aktif pada penyakit autoimun.', tr: 'Otoimmün hastalıklarda aşırı aktif bağışıklık sistemini sakinleştirir.', ru: 'Успокаивает сверхактивную иммунную систему при аутоиммунных заболеваниях.', ar: 'يهدئ الجهاز المناعي المفرط النشاط في أمراض المناعة الذاتية.', hi: 'ऑटोइम्यून बीमारियों में अति सक्रिय प्रतिरक्षा प्रणाली को शांत करता है।' },
  'Reduces immune activity in autoimmune disease.': {
    ja: '自己免疫疾患での免疫の働きを抑えます。', zh: '减少自身免疫性疾病中的免疫活动。', es: 'Reduce la actividad inmune en enfermedades autoinmunes.', fr: 'Réduit l’activité immunitaire dans les maladies auto-immunes.', de: 'Reduziert die Immunaktivität bei Autoimmunerkrankungen.', pt: 'Reduz a atividade imunológica em doenças autoimunes.', it: 'Riduce l’attività immunitaria nelle malattie autoimmuni.', ko: '자가면역 질환에서 면역 활동을 억제합니다.', th: 'ลดการทำงานของภูมิคุ้มกันในโรคภูมิต้านตนเอง', vi: 'Giảm hoạt động miễn dịch trong bệnh tự miễn.', id: 'Mengurangi aktivitas imun pada penyakit autoimun.', tr: 'Otoimmün hastalıklarda bağışıklık aktivitesini azaltır.', ru: 'Снижает активность иммунитета при аутоиммунных заболеваниях.', ar: 'يقلل نشاط المناعة في أمراض المناعة الذاتية.', hi: 'ऑटोइम्यून बीमारियों में प्रतिरक्षा गतिविधि कम करता है।' },
  'Reduces inflammation in autoimmune disease.': {
    ja: '自己免疫疾患の炎症を抑えます。', zh: '减轻自身免疫性疾病中的炎症。', es: 'Reduce la inflamación en enfermedades autoinmunes.', fr: 'Réduit l’inflammation dans les maladies auto-immunes.', de: 'Reduziert Entzündungen bei Autoimmunerkrankungen.', pt: 'Reduz a inflamação em doenças autoimunes.', it: 'Riduce l’infiammazione nelle malattie autoimmuni.', ko: '자가면역 질환의 염증을 줄입니다.', th: 'ลดการอักเสบในโรคภูมิต้านตนเอง', vi: 'Giảm viêm trong bệnh tự miễn.', id: 'Mengurangi peradangan pada penyakit autoimun.', tr: 'Otoimmün hastalıklarda iltihabı azaltır.', ru: 'Снижает воспаление при аутоиммунных заболеваниях.', ar: 'يقلل الالتهاب في أمراض المناعة الذاتية.', hi: 'ऑटोइम्यून बीमारियों में सूजन कम करता है।' },
  'Reduces inflammation in IBD and autoimmune disease.': {
    ja: '炎症性腸疾患や自己免疫疾患の炎症を抑えます。', zh: '减轻炎症性肠病和自身免疫性疾病中的炎症。', es: 'Reduce la inflamación en la EII y enfermedades autoinmunes.', fr: 'Réduit l’inflammation dans les MII et les maladies auto-immunes.', de: 'Reduziert Entzündungen bei chronisch-entzündlichen Darmerkrankungen und Autoimmunerkrankungen.', pt: 'Reduz inflamação em DII e doenças autoimunes.', it: 'Riduce l’infiammazione nelle MICI e nelle malattie autoimmuni.', ko: '염증성 장질환과 자가면역 질환의 염증을 줄입니다.', th: 'ลดการอักเสบในโรคลำไส้อักเสบและโรคภูมิต้านตนเอง', vi: 'Giảm viêm trong bệnh viêm ruột và bệnh tự miễn.', id: 'Mengurangi peradangan pada IBD dan penyakit autoimun.', tr: 'İBH ve otoimmün hastalıklarda iltihabı azaltır.', ru: 'Снижает воспаление при ВЗК и аутоиммунных заболеваниях.', ar: 'يقلل الالتهاب في مرض الأمعاء الالتهابي وأمراض المناعة الذاتية.', hi: 'आईबीडी और ऑटोइम्यून बीमारियों में सूजन कम करता है।' },
  'Reduces inflammation in RA and related conditions.': {
    ja: '関節リウマチなど関連疾患の炎症を抑えます。', zh: '减轻类风湿关节炎及相关疾病的炎症。', es: 'Reduce la inflamación en la AR y afecciones relacionadas.', fr: 'Réduit l’inflammation dans la PR et les affections associées.', de: 'Reduziert Entzündungen bei rheumatoider Arthritis und verwandten Erkrankungen.', pt: 'Reduz inflamação na AR e condições relacionadas.', it: 'Riduce l’infiammazione nell’AR e condizioni correlate.', ko: '류마티스 관절염 등 관련 질환의 염증을 줄입니다.', th: 'ลดการอักเสบในข้ออักเสบรูมาตอยด์และโรคที่เกี่ยวข้อง', vi: 'Giảm viêm trong viêm khớp dạng thấp và các bệnh liên quan.', id: 'Mengurangi peradangan pada RA dan kondisi terkait.', tr: 'RA ve ilgili durumlarda iltihabı azaltır.', ru: 'Снижает воспаление при ревматоидном артрите и родственных заболеваниях.', ar: 'يقلل الالتهاب في التهاب المفاصل الروماتويدي والحالات ذات الصلة.', hi: 'आरए और संबंधित स्थितियों में सूजन कम करता है।' },
  'Treats certain autoimmune and blood conditions.': {
    ja: '特定の自己免疫疾患や血液疾患を治療します。', zh: '治疗某些自身免疫性和血液疾病。', es: 'Trata ciertas enfermedades autoinmunes y sanguíneas.', fr: 'Traite certaines maladies auto-immunes et sanguines.', de: 'Behandelt bestimmte Autoimmun- und Bluterkrankungen.', pt: 'Trata certas doenças autoimunes e do sangue.', it: 'Tratta alcune malattie autoimmuni e del sangue.', ko: '특정 자가면역 질환과 혈액 질환을 치료합니다.', th: 'รักษาโรคภูมิต้านตนเองและโรคเลือดบางชนิด', vi: 'Điều trị một số bệnh tự miễn và bệnh về máu.', id: 'Mengobati penyakit autoimun dan darah tertentu.', tr: 'Belirli otoimmün ve kan hastalıklarını tedavi eder.', ru: 'Лечит некоторые аутоиммунные и кровяные заболевания.', ar: 'يعالج بعض أمراض المناعة الذاتية والدم.', hi: 'कुछ ऑटोइम्यून और रक्त स्थितियों का उपचार करता है।' },
  'Treats gout attacks and related inflammation.': {
    ja: '痛風発作と関連する炎症を治療します。', zh: '治疗痛风发作及相关炎症。', es: 'Trata los ataques de gota y la inflamación relacionada.', fr: 'Traite les crises de goutte et l’inflammation associée.', de: 'Behandelt Gichtanfälle und damit verbundene Entzündungen.', pt: 'Trata crises de gota e inflamação relacionada.', it: 'Tratta gli attacchi di gotta e l’infiammazione correlata.', ko: '통풍 발작과 관련 염증을 치료합니다.', th: 'รักษาอาการกำเริบของโรคเกาต์และการอักเสบที่เกี่ยวข้อง', vi: 'Điều trị cơn gút và viêm liên quan.', id: 'Mengobati serangan asam urat dan peradangan terkait.', tr: 'Gut ataklarını ve ilgili iltihabı tedavi eder.', ru: 'Лечит приступы подагры и связанное воспаление.', ar: 'يعالج نوبات النقرس والالتهاب المرتبط بها.', hi: 'गाउट के दौरे और संबंधित सूजन का उपचार करता है।' },
  'Reduces stomach acid for heartburn and reflux.': {
    ja: '胸やけ・逆流の胃酸を抑えます。', zh: '减少胃酸，缓解烧心和反流。', es: 'Reduce el ácido estomacal para la acidez y el reflujo.', fr: 'Réduit l’acidité de l’estomac contre les brûlures et le reflux.', de: 'Reduziert Magensäure bei Sodbrennen und Reflux.', pt: 'Reduz o ácido do estômago para azia e refluxo.', it: 'Riduce l’acidità di stomaco per bruciore e reflusso.', ko: '속쓰림과 역류를 위한 위산을 줄입니다.', th: 'ลดกรดในกระเพาะสำหรับอาการแสบร้อนกลางอกและกรดไหลย้อน', vi: 'Giảm axit dạ dày cho chứng ợ nóng và trào ngược.', id: 'Mengurangi asam lambung untuk nyeri ulu hati dan refluks.', tr: 'Mide yanması ve reflü için mide asidini azaltır.', ru: 'Снижает кислотность желудка при изжоге и рефлюксе.', ar: 'يقلل حمض المعدة لعلاج الحرقة والارتجاع.', hi: 'सीने की जलन और एसिड रिफ्लक्स के लिए पेट का एसिड कम करता है।' },
  'Reduces stomach acid for reflux and ulcers.': {
    ja: '逆流・潰瘍の胃酸を抑えます。', zh: '减少胃酸，缓解反流和溃疡。', es: 'Reduce el ácido estomacal para el reflujo y las úlceras.', fr: 'Réduit l’acidité pour le reflux et les ulcères.', de: 'Reduziert Magensäure bei Reflux und Geschwüren.', pt: 'Reduz o ácido do estômago para refluxo e úlceras.', it: 'Riduce l’acidità di stomaco per reflusso e ulcere.', ko: '역류와 궤양을 위한 위산을 줄입니다.', th: 'ลดกรดในกระเพาะสำหรับกรดไหลย้อนและแผลในกระเพาะ', vi: 'Giảm axit dạ dày cho trào ngược và loét.', id: 'Mengurangi asam lambung untuk refluks dan tukak.', tr: 'Reflü ve ülser için mide asidini azaltır.', ru: 'Снижает кислотность желудка при рефлюксе и язвах.', ar: 'يقلل حمض المعدة للارتجاع والقرحة.', hi: 'रिफ्लक्स और अल्सर के लिए पेट का एसिड कम करता है।' },
  'Reduces stomach acid for reflux.': {
    ja: '逆流の胃酸を抑えます。', zh: '减少胃酸，缓解反流。', es: 'Reduce el ácido estomacal para el reflujo.', fr: 'Réduit l’acidité contre le reflux.', de: 'Reduziert Magensäure bei Reflux.', pt: 'Reduz o ácido do estômago para refluxo.', it: 'Riduce l’acidità di stomaco per il reflusso.', ko: '역류를 위한 위산을 줄입니다.', th: 'ลดกรดในกระเพาะสำหรับกรดไหลย้อน', vi: 'Giảm axit dạ dày cho trào ngược.', id: 'Mengurangi asam lambung untuk refluks.', tr: 'Reflü için mide asidini azaltır.', ru: 'Снижает кислотность желудка при рефлюксе.', ar: 'يقلل حمض المعدة للارتجاع.', hi: 'रिफ्लक्स के लिए पेट का एसिड कम करता है।' },
  'Reduces stomach acid for heartburn.': {
    ja: '胸やけの胃酸を抑えます。', zh: '减少胃酸，缓解烧心。', es: 'Reduce el ácido estomacal para la acidez.', fr: 'Réduit l’acidité contre les brûlures d’estomac.', de: 'Reduziert Magensäure bei Sodbrennen.', pt: 'Reduz o ácido do estômago para azia.', it: 'Riduce l’acidità di stomaco per il bruciore.', ko: '속쓰림을 위한 위산을 줄입니다.', th: 'ลดกรดในกระเพาะสำหรับอาการแสบร้อนกลางอก', vi: 'Giảm axit dạ dày cho chứng ợ nóng.', id: 'Mengurangi asam lambung untuk nyeri ulu hati.', tr: 'Mide yanması için mide asidini azaltır.', ru: 'Снижает кислотность желудка при изжоге.', ar: 'يقلل حمض المعدة للحرقة.', hi: 'सीने की जलन के लिए पेट का एसिड कम करता है।' },
  'Relieves nausea, vomiting, and slow stomach emptying.': {
    ja: '吐き気・嘔吐・胃内容排出遅延を和らげます。', zh: '缓解恶心、呕吐和胃排空缓慢。', es: 'Alivia náuseas, vómitos y el vaciado lento del estómago.', fr: 'Soulage les nausées, vomissements et le ralentissement de la vidange de l’estomac.', de: 'Lindert Übelkeit, Erbrechen und verlangsamte Magenentleerung.', pt: 'Alivia náuseas, vômitos e esvaziamento lento do estômago.', it: 'Allevia nausea, vomito e svuotamento gastrico lento.', ko: '메스꺼움·구토·위배출 지연을 완화합니다.', th: 'บรรเทาอาการคลื่นไส้ อาเจียน และกระเพาะย่อยช้า', vi: 'Giảm buồn nôn, nôn và chậm tiêu hóa dạ dày.', id: 'Meredakan mual, muntah, dan pengosongan lambung lambat.', tr: 'Bulantı, kusma ve yavaş mide boşalmasını giderir.', ru: 'Снимает тошноту, рвоту и замедленное опорожнение желудка.', ar: 'يخفف الغثيان والقيء وبطء إفراغ المعدة.', hi: 'मतली, उल्टी और धीमी गैस्ट्रिक खाली होने से राहत देता है।' },
  'Prevents nausea and vomiting.': {
    ja: '吐き気と嘔吐を防ぎます。', zh: '预防恶心和呕吐。', es: 'Previene las náuseas y los vómitos.', fr: 'Prévient les nausées et vomissements.', de: 'Beugt Übelkeit und Erbrechen vor.', pt: 'Previne náuseas e vômitos.', it: 'Previene nausea e vomito.', ko: '메스꺼움과 구토를 예방합니다.', th: 'ป้องกันอาการคลื่นไส้และอาเจียน', vi: 'Ngăn ngừa buồn nôn và nôn.', id: 'Mencegah mual dan muntah.', tr: 'Bulantı ve kusmayı önler.', ru: 'Предотвращает тошноту и рвоту.', ar: 'يمنع الغثيان والقيء.', hi: 'मतली और उल्टी को रोकता है।' },
  'Stops diarrhea.': {
    ja: '下痢を止めます。', zh: '止泻。', es: 'Detiene la diarrea.', fr: 'Arrête la diarrhée.', de: 'Stoppt Durchfall.', pt: 'Interrompe a diarreia.', it: 'Ferma la diarrea.', ko: '설사를 멈춥니다.', th: 'หยุดอาการท้องเสีย', vi: 'Ngăn tiêu chảy.', id: 'Menghentikan diare.', tr: 'İshali durdurur.', ru: 'Останавливает диарею.', ar: 'يوقف الإسهال.', hi: 'दस्त रोकता है।' },
  'Relieves diarrhea and upset stomach.': {
    ja: '下痢と胃の不調を和らげます。', zh: '缓解腹泻和胃部不适。', es: 'Alivia la diarrea y el malestar estomacal.', fr: 'Soulage la diarrhée et les maux d’estomac.', de: 'Lindert Durchfall und Magenverstimmung.', pt: 'Alivia diarreia e indisposição estomacal.', it: 'Allevia diarrea e disturbi di stomaco.', ko: '설사와 위장 불편을 완화합니다.', th: 'บรรเทาอาการท้องเสียและท้องไส้ปั่นป่วน', vi: 'Giảm tiêu chảy và khó chịu dạ dày.', id: 'Meredakan diare dan gangguan perut.', tr: 'İshali ve mide rahatsızlığını giderir.', ru: 'Снимает диарею и расстройство желудка.', ar: 'يخفف الإسهال واضطراب المعدة.', hi: 'दस्त और पेट की गड़बड़ी से राहत देता है।' },
  'Reduces colon inflammation in ulcerative colitis.': {
    ja: '潰瘍性大腸炎の大腸の炎症を抑えます。', zh: '减轻溃疡性结肠炎中的结肠炎症。', es: 'Reduce la inflamación del colon en la colitis ulcerosa.', fr: 'Réduit l’inflammation du côlon dans la rectocolite hémorragique.', de: 'Reduziert Dickdarmentzündungen bei Colitis ulcerosa.', pt: 'Reduz a inflamação do cólon na colite ulcerativa.', it: 'Riduce l’infiammazione del colon nella colite ulcerosa.', ko: '궤양성 대장염의 대장 염증을 줄입니다.', th: 'ลดการอักเสบของลำไส้ใหญ่ในโรคลำไส้ใหญ่อักเสบเป็นแผล', vi: 'Giảm viêm đại tràng trong viêm loét đại tràng.', id: 'Mengurangi peradangan usus besar pada kolitis ulseratif.', tr: 'Ülseratif kolitte kolon iltihabını azaltır.', ru: 'Снижает воспаление толстой кишки при язвенном колите.', ar: 'يقلل التهاب القولون في التهاب القولون التقرحي.', hi: 'अल्सरेटिव कोलाइटिस में बृहदान्त्र की सूजन कम करता है।' },
  'Reduces bowel inflammation in IBD.': {
    ja: '炎症性腸疾患の腸の炎症を抑えます。', zh: '减轻炎症性肠病中的肠道炎症。', es: 'Reduce la inflamación intestinal en la EII.', fr: 'Réduit l’inflammation intestinale dans les MII.', de: 'Reduziert Darmentzündungen bei chronisch-entzündlichen Darmerkrankungen.', pt: 'Reduz a inflamação intestinal em DII.', it: 'Riduce l’infiammazione intestinale nelle MICI.', ko: '염증성 장질환의 장 염증을 줄입니다.', th: 'ลดการอักเสบของลำไส้ในโรคลำไส้อักเสบ', vi: 'Giảm viêm ruột trong bệnh viêm ruột.', id: 'Mengurangi peradangan usus pada IBD.', tr: 'İBH’da bağırsak iltihabını azaltır.', ru: 'Снижает воспаление кишечника при ВЗК.', ar: 'يقلل التهاب الأمعاء في مرض الأمعاء الالتهابي.', hi: 'आईबीडी में आंत की सूजन कम करता है।' },
  'Relieves stomach cramps and IBS pain.': {
    ja: '胃のけいれんと過敏性腸症候群の痛みを和らげます。', zh: '缓解胃痉挛和肠易激综合征疼痛。', es: 'Alivia los calambres estomacales y el dolor del SII.', fr: 'Soulage les crampes d’estomac et les douleurs du SII.', de: 'Lindert Magenkrämpfe und Schmerzen bei Reizdarm.', pt: 'Alivia cólicas estomacais e dor da SII.', it: 'Allevia crampi allo stomaco e dolore da IBS.', ko: '위 경련과 과민성 대장 증후군의 통증을 완화합니다.', th: 'บรรเทาปวดท้องและอาการปวดจากลำไส้แปรปรวน', vi: 'Giảm co thắt dạ dày và đau hội chứng ruột kích thích.', id: 'Meredakan kram perut dan nyeri IBS.', tr: 'Mide kramplarını ve IBS ağrısını giderir.', ru: 'Снимает спазмы желудка и боль при СРК.', ar: 'يخفف تقلصات المعدة وألم متلازمة القولون العصبي.', hi: 'पेट की ऐंठन और आईबीएस दर्द से राहत देता है।' },
  'Relieves constipation.': {
    ja: '便秘を和らげます。', zh: '缓解便秘。', es: 'Alivia el estreñimiento.', fr: 'Soulage la constipation.', de: 'Lindert Verstopfung.', pt: 'Alivia a constipação.', it: 'Allevia la stitichezza.', ko: '변비를 완화합니다.', th: 'บรรเทาอาการท้องผูก', vi: 'Giảm táo bón.', id: 'Meredakan sembelit.', tr: 'Kabızlığı giderir.', ru: 'Снимает запор.', ar: 'يخفف الإمساك.', hi: 'कब्ज से राहत देता है।' },
  'Relieves constipation or diarrhea.': {
    ja: '便秘や下痢を和らげます。', zh: '缓解便秘或腹泻。', es: 'Alivia el estreñimiento o la diarrea.', fr: 'Soulage la constipation ou la diarrhée.', de: 'Lindert Verstopfung oder Durchfall.', pt: 'Alivia constipação ou diarreia.', it: 'Allevia stitichezza o diarrea.', ko: '변비나 설사를 완화합니다.', th: 'บรรเทาอาการท้องผูกหรือท้องเสีย', vi: 'Giảm táo bón hoặc tiêu chảy.', id: 'Meredakan sembelit atau diare.', tr: 'Kabızlığı veya ishali giderir.', ru: 'Снимает запор или диарею.', ar: 'يخفف الإمساك أو الإسهال.', hi: 'कब्ज या दस्त से राहत देता है।' },
  'Lowers blood sugar in type 2 diabetes.': {
    ja: '2型糖尿病の血糖値を下げます。', zh: '降低2型糖尿病的血糖。', es: 'Reduce el azúcar en sangre en la diabetes tipo 2.', fr: 'Réduit la glycémie dans le diabète de type 2.', de: 'Senkt den Blutzucker bei Typ-2-Diabetes.', pt: 'Reduz o açúcar no sangue no diabetes tipo 2.', it: 'Riduce la glicemia nel diabete di tipo 2.', ko: '2형 당뇨병의 혈당을 낮춥니다.', th: 'ลดน้ำตาลในเลือดในเบาหวานชนิดที่ 2', vi: 'Giảm đường huyết ở bệnh tiểu đường type 2.', id: 'Menurunkan gula darah pada diabetes tipe 2.', tr: 'Tip 2 diyabette kan şekerini düşürür.', ru: 'Снижает сахар в крови при диабете 2 типа.', ar: 'يخفض سكر الدم في داء السكري من النوع 2.', hi: 'टाइप 2 मधुमेह में रक्त शर्करा कम करता है।' },
  'Lowers blood sugar; also protects heart and kidneys.': {
    ja: '血糖値を下げ、心臓と腎臓も保護します。', zh: '降低血糖，同时保护心脏和肾脏。', es: 'Reduce el azúcar en sangre y protege el corazón y los riñones.', fr: 'Réduit la glycémie et protège aussi le cœur et les reins.', de: 'Senkt den Blutzucker und schützt zusätzlich Herz und Nieren.', pt: 'Reduz o açúcar no sangue e também protege o coração e os rins.', it: 'Riduce la glicemia e protegge anche cuore e reni.', ko: '혈당을 낮추고 심장과 신장도 보호합니다.', th: 'ลดน้ำตาลในเลือดและยังปกป้องหัวใจและไต', vi: 'Giảm đường huyết, đồng thời bảo vệ tim và thận.', id: 'Menurunkan gula darah dan melindungi jantung serta ginjal.', tr: 'Kan şekerini düşürür; ayrıca kalbi ve böbrekleri korur.', ru: 'Снижает сахар в крови, а также защищает сердце и почки.', ar: 'يخفض سكر الدم ويحمي القلب والكلى أيضًا.', hi: 'रक्त शर्करा कम करता है; हृदय और गुर्दे की भी रक्षा करता है।' },
  'Lowers blood sugar and supports weight loss.': {
    ja: '血糖値を下げ、体重減少を助けます。', zh: '降低血糖并帮助减重。', es: 'Reduce el azúcar en sangre y favorece la pérdida de peso.', fr: 'Réduit la glycémie et favorise la perte de poids.', de: 'Senkt den Blutzucker und unterstützt die Gewichtsabnahme.', pt: 'Reduz o açúcar no sangue e apoia a perda de peso.', it: 'Riduce la glicemia e favorisce la perdita di peso.', ko: '혈당을 낮추고 체중 감량을 돕습니다.', th: 'ลดน้ำตาลในเลือดและช่วยลดน้ำหนัก', vi: 'Giảm đường huyết và hỗ trợ giảm cân.', id: 'Menurunkan gula darah dan mendukung penurunan berat badan.', tr: 'Kan şekerini düşürür ve kilo kaybını destekler.', ru: 'Снижает сахар в крови и способствует снижению веса.', ar: 'يخفض سكر الدم ويساعد على فقدان الوزن.', hi: 'रक्त शर्करा कम करता है और वजन घटाने में सहायता करता है।' },
}
