// 약 설명 문장 번역 (40~78) — 키는 영어 원문, 값은 15개 언어 번역
import type { InfoTrans } from './medsInfo1'

export const INFOS_PART2: Record<string, InfoTrans> = {
  'Lowers blood sugar in diabetes.': {
    ja: '糖尿病の血糖値を下げます。', zh: '降低糖尿病的血糖。', es: 'Reduce el azúcar en sangre en la diabetes.', fr: 'Réduit la glycémie dans le diabète.', de: 'Senkt den Blutzucker bei Diabetes.', pt: 'Reduz o açúcar no sangue no diabetes.', it: 'Riduce la glicemia nel diabete.', ko: '당뇨병의 혈당을 낮춥니다.', th: 'ลดน้ำตาลในเลือดในโรคเบาหวาน', vi: 'Giảm đường huyết ở bệnh tiểu đường.', id: 'Menurunkan gula darah pada diabetes.', tr: 'Diyabette kan şekerini düşürür.', ru: 'Снижает сахар в крови при диабете.', ar: 'يخفض سكر الدم في مرض السكري.', hi: 'मधुमेह में रक्त शर्करा कम करता है।' },
  'Replaces missing thyroid hormone.': {
    ja: '不足した甲状腺ホルモンを補います。', zh: '补充缺失的甲状腺激素。', es: 'Reemplaza la hormona tiroidea faltante.', fr: 'Remplace l’hormone thyroïdienne manquante.', de: 'Ersetzt fehlendes Schilddrüsenhormon.', pt: 'Repõe o hormônio da tireoide em falta.', it: 'Sostituisce l’ormone tiroideo mancante.', ko: '부족한 갑상선 호르몬을 보충합니다.', th: 'ทดแทนฮอร์โมนไทรอยด์ที่ขาด', vi: 'Bổ sung hormone tuyến giáp bị thiếu.', id: 'Menggantikan hormon tiroid yang kurang.', tr: 'Eksik tiroid hormonunu yerine koyar.', ru: 'Восполняет недостаток гормона щитовидной железы.', ar: 'يعوض نقص هرمون الغدة الدرقية.', hi: 'कमी वाले थायराइड हार्मोन की पूर्ति करता है।' },
  'Prevents gout attacks by lowering uric acid.': {
    ja: '尿酸を下げて痛風発作を防ぎます。', zh: '通过降低尿酸预防痛风发作。', es: 'Previene los ataques de gota al reducir el ácido úrico.', fr: 'Prévient les crises de goutte en réduisant l’acide urique.', de: 'Beugt Gichtanfällen vor, indem es Harnsäure senkt.', pt: 'Previne crises de gota ao reduzir o ácido úrico.', it: 'Previene gli attacchi di gotta riducendo l’acido urico.', ko: '요산을 낮춰 통풍 발작을 예방합니다.', th: 'ป้องกันอาการกำเริบของโรคเกาต์โดยลดกรดยูริก', vi: 'Ngăn cơn gút bằng cách giảm axit uric.', id: 'Mencegah serangan asam urat dengan menurunkan asam urat.', tr: 'Ürik asidi düşürerek gut ataklarını önler.', ru: 'Предотвращает приступы подагры, снижая мочевую кислоту.', ar: 'يمنع نوبات النقرس بخفض حمض اليوريك.', hi: 'यूरिक एसिड कम करके गाउट के दौरे रोकता है।' },
  'Lowers cholesterol to protect the heart.': {
    ja: 'コレステロールを下げて心臓を守ります。', zh: '降低胆固醇以保护心脏。', es: 'Reduce el colesterol para proteger el corazón.', fr: 'Réduit le cholestérol pour protéger le cœur.', de: 'Senkt das Cholesterin und schützt das Herz.', pt: 'Reduz o colesterol para proteger o coração.', it: 'Riduce il colesterolo per proteggere il cuore.', ko: '콜레스테롤을 낮춰 심장을 보호합니다.', th: 'ลดคอเลสเตอรอลเพื่อปกป้องหัวใจ', vi: 'Giảm cholesterol để bảo vệ tim.', id: 'Menurunkan kolesterol untuk melindungi jantung.', tr: 'Kalbi korumak için kolesterolü düşürür.', ru: 'Снижает холестерин для защиты сердца.', ar: 'يخفض الكوليسترول لحماية القلب.', hi: 'हृदय की रक्षा के लिए कोलेस्ट्रॉल कम करता है।' },
  'Lowers cholesterol.': {
    ja: 'コレステロールを下げます。', zh: '降低胆固醇。', es: 'Reduce el colesterol.', fr: 'Réduit le cholestérol.', de: 'Senkt das Cholesterin.', pt: 'Reduz o colesterol.', it: 'Riduce il colesterolo.', ko: '콜레스테롤을 낮춥니다.', th: 'ลดคอเลสเตอรอล', vi: 'Giảm cholesterol.', id: 'Menurunkan kolesterol.', tr: 'Kolesterolü düşürür.', ru: 'Снижает холестерин.', ar: 'يخفض الكوليسترول.', hi: 'कोलेस्ट्रॉल कम करता है।' },
  'Lowers blood pressure.': {
    ja: '血圧を下げます。', zh: '降低血压。', es: 'Reduce la presión arterial.', fr: 'Réduit la tension artérielle.', de: 'Senkt den Blutdruck.', pt: 'Reduz a pressão arterial.', it: 'Riduce la pressione sanguigna.', ko: '혈압을 낮춥니다.', th: 'ลดความดันโลหิต', vi: 'Giảm huyết áp.', id: 'Menurunkan tekanan darah.', tr: 'Tansiyonu düşürür.', ru: 'Снижает давление.', ar: 'يخفض ضغط الدم.', hi: 'रक्तचाप कम करता है।' },
  'Lowers blood pressure; protects the kidneys.': {
    ja: '血圧を下げ、腎臓を保護します。', zh: '降低血压并保护肾脏。', es: 'Reduce la presión arterial y protege los riñones.', fr: 'Réduit la tension artérielle et protège les reins.', de: 'Senkt den Blutdruck und schützt die Nieren.', pt: 'Reduz a pressão arterial e protege os rins.', it: 'Riduce la pressione sanguigna e protegge i reni.', ko: '혈압을 낮추고 신장을 보호합니다.', th: 'ลดความดันโลหิตและปกป้องไต', vi: 'Giảm huyết áp và bảo vệ thận.', id: 'Menurunkan tekanan darah dan melindungi ginjal.', tr: 'Tansiyonu düşürür; böbrekleri korur.', ru: 'Снижает давление и защищает почки.', ar: 'يخفض ضغط الدم ويحمي الكلى.', hi: 'रक्तचाप कम करता है; गुर्दों की रक्षा करता है।' },
  'Lowers blood pressure and heart rate.': {
    ja: '血圧と心拍数を下げます。', zh: '降低血压和心率。', es: 'Reduce la presión arterial y la frecuencia cardíaca.', fr: 'Réduit la tension artérielle et la fréquence cardiaque.', de: 'Senkt Blutdruck und Herzfrequenz.', pt: 'Reduz a pressão arterial e a frequência cardíaca.', it: 'Riduce pressione sanguigna e frequenza cardiaca.', ko: '혈압과 심박수를 낮춥니다.', th: 'ลดความดันโลหิตและอัตราการเต้นของหัวใจ', vi: 'Giảm huyết áp và nhịp tim.', id: 'Menurunkan tekanan darah dan detak jantung.', tr: 'Tansiyonu ve kalp atışını düşürür.', ru: 'Снижает давление и частоту сердечных сокращений.', ar: 'يخفض ضغط الدم ومعدل ضربات القلب.', hi: 'रक्तचाप और हृदय गति कम करता है।' },
  'Lowers blood pressure; also prevents migraines.': {
    ja: '血圧を下げ、片頭痛も予防します。', zh: '降低血压，同时预防偏头痛。', es: 'Reduce la presión arterial y también previene migrañas.', fr: 'Réduit la tension artérielle et prévient aussi les migraines.', de: 'Senkt den Blutdruck und beugt auch Migräne vor.', pt: 'Reduz a pressão arterial e também previne enxaquecas.', it: 'Riduce la pressione sanguigna e previene anche le emicranie.', ko: '혈압을 낮추고 편두통도 예방합니다.', th: 'ลดความดันโลหิตและป้องกันไมเกรน', vi: 'Giảm huyết áp và ngăn ngừa đau nửa đầu.', id: 'Menurunkan tekanan darah dan mencegah migrain.', tr: 'Tansiyonu düşürür; migreni de önler.', ru: 'Снижает давление и предотвращает мигрень.', ar: 'يخفض ضغط الدم ويمنع الصداع النصفي.', hi: 'रक्तचाप कम करता है; माइग्रेन भी रोकता है।' },
  'Removes excess fluid from the body (edema).': {
    ja: '体の余分な水分(むくみ)を取り除きます。', zh: '排出体内多余液体（水肿）。', es: 'Elimina el exceso de líquido del cuerpo (edema).', fr: 'Élimine l’excès de liquide du corps (œdème).', de: 'Entfernt überschüssige Flüssigkeit aus dem Körper (Ödem).', pt: 'Remove o excesso de líquido do corpo (edema).', it: 'Rimuove il liquido in eccesso dal corpo (edema).', ko: '체내 과잉 수분(부종)을 제거합니다.', th: 'ขจัดของเหลวส่วนเกินออกจากร่างกาย (บวมน้ำ)', vi: 'Loại bỏ chất lỏng dư thừa khỏi cơ thể (phù nề).', id: 'Mengeluarkan kelebihan cairan dari tubuh (edema).', tr: 'Vücuttaki fazla sıvıyı atar (ödem).', ru: 'Выводит лишнюю жидкость из организма (отёки).', ar: 'يزيل السوائل الزائدة من الجسم (الوذمة).', hi: 'शरीर से अतिरिक्त तरल निकालता है (एडिमा)।' },
  'Lowers blood pressure and removes excess fluid.': {
    ja: '血圧を下げ、余分な水分を取り除きます。', zh: '降低血压并排出多余液体。', es: 'Reduce la presión arterial y elimina el exceso de líquido.', fr: 'Réduit la tension artérielle et élimine l’excès de liquide.', de: 'Senkt den Blutdruck und entfernt überschüssige Flüssigkeit.', pt: 'Reduz a pressão arterial e remove o excesso de líquido.', it: 'Riduce la pressione sanguigna e rimuove il liquido in eccesso.', ko: '혈압을 낮추고 과잉 수분을 제거합니다.', th: 'ลดความดันโลหิตและขจัดของเหลวส่วนเกิน', vi: 'Giảm huyết áp và loại bỏ chất lỏng dư thừa.', id: 'Menurunkan tekanan darah dan mengeluarkan kelebihan cairan.', tr: 'Tansiyonu düşürür ve fazla sıvıyı atar.', ru: 'Снижает давление и выводит лишнюю жидкость.', ar: 'يخفض ضغط الدم ويزيل السوائل الزائدة.', hi: 'रक्तचाप कम करता है और अतिरिक्त तरल निकालता है।' },
  'Removes excess fluid; used for heart failure and hormonal conditions.': {
    ja: '余分な水分を取り除き、心不全やホルモン疾患に用います。', zh: '排出多余液体；用于心力衰竭和激素相关疾病。', es: 'Elimina el exceso de líquido; se usa en insuficiencia cardíaca y trastornos hormonales.', fr: 'Élimine l’excès de liquide ; utilisé dans l’insuffisance cardiaque et les troubles hormonaux.', de: 'Entfernt überschüssige Flüssigkeit; bei Herzinsuffizienz und hormonellen Erkrankungen.', pt: 'Remove o excesso de líquido; usado em insuficiência cardíaca e condições hormonais.', it: 'Rimuove il liquido in eccesso; usato nello scompenso cardiaco e nelle condizioni ormonali.', ko: '과잉 수분을 제거하고 심부전·호르몬 질환에 사용합니다.', th: 'ขจัดของเหลวส่วนเกิน ใช้ในภาวะหัวใจล้มเหลวและโรคฮอร์โมน', vi: 'Loại bỏ chất lỏng dư thừa; dùng cho suy tim và rối loạn nội tiết.', id: 'Mengeluarkan kelebihan cairan; digunakan pada gagal jantung dan kondisi hormonal.', tr: 'Fazla sıvıyı atar; kalp yetmezliği ve hormonal durumlarda kullanılır.', ru: 'Выводит лишнюю жидкость; используется при сердечной недостаточности и гормональных нарушениях.', ar: 'يزيل السوائل الزائدة؛ يُستخدم في قصور القلب والحالات الهرمونية.', hi: 'अतिरिक्त तरल निकालता है; हृदय विफलता और हार्मोनल स्थितियों में उपयोग।' },
  'Prevents blood clots.': {
    ja: '血栓を防ぎます。', zh: '预防血栓。', es: 'Previene los coágulos de sangre.', fr: 'Prévient les caillots sanguins.', de: 'Beugt Blutgerinnseln vor.', pt: 'Previne coágulos sanguíneos.', it: 'Previene i coaguli di sangue.', ko: '혈전을 예방합니다.', th: 'ป้องกันลิ่มเลือด', vi: 'Ngăn ngừa cục máu đông.', id: 'Mencegah penggumpalan darah.', tr: 'Kan pıhtılarını önler.', ru: 'Предотвращает образование тромбов.', ar: 'يمنع جلطات الدم.', hi: 'रक्त के थक्के रोकता है।' },
  'Prevents blood clots and heart attacks.': {
    ja: '血栓と心筋梗塞を防ぎます。', zh: '预防血栓和心脏病发作。', es: 'Previene coágulos y ataques cardíacos.', fr: 'Prévient les caillots et les crises cardiaques.', de: 'Beugt Blutgerinnseln und Herzinfarkten vor.', pt: 'Previne coágulos e ataques cardíacos.', it: 'Previene coaguli e attacchi di cuore.', ko: '혈전과 심장마비를 예방합니다.', th: 'ป้องกันลิ่มเลือดและอาการหัวใจวาย', vi: 'Ngăn ngừa cục máu đông và đau tim.', id: 'Mencegah penggumpalan darah dan serangan jantung.', tr: 'Kan pıhtılarını ve kalp krizini önler.', ru: 'Предотвращает тромбы и инфаркты.', ar: 'يمنع الجلطات والنوبات القلبية.', hi: 'रक्त के थक्के और दिल के दौरे रोकता है।' },
  'Relieves angina (chest pain).': {
    ja: '狭心症(胸の痛み)を和らげます。', zh: '缓解心绞痛（胸痛）。', es: 'Alivia la angina (dolor de pecho).', fr: 'Soulage l’angine de poitrine (douleur thoracique).', de: 'Lindert Angina pectoris (Brustschmerz).', pt: 'Alivia a angina (dor no peito).', it: 'Allevia l’angina (dolore al petto).', ko: '협심증(흉통)을 완화합니다.', th: 'บรรเทาอาการเจ็บหน้าอกจากหลอดเลือดหัวใจตีบ', vi: 'Giảm cơn đau thắt ngực (đau ngực).', id: 'Meredakan angina (nyeri dada).', tr: 'Anginayı (göğüs ağrısını) giderir.', ru: 'Снимает стенокардию (боль в груди).', ar: 'يخفف الذبحة الصدرية (ألم الصدر).', hi: 'एनजाइना (सीने में दर्द) से राहत देता है।' },
  'Treats heart failure and irregular heartbeat.': {
    ja: '心不全と不整脈を治療します。', zh: '治疗心力衰竭和心律不齐。', es: 'Trata la insuficiencia cardíaca y el ritmo cardíaco irregular.', fr: 'Traite l’insuffisance cardiaque et les battements irréguliers.', de: 'Behandelt Herzinsuffizienz und unregelmäßigen Herzschlag.', pt: 'Trata insuficiência cardíaca e batimentos irregulares.', it: 'Tratta lo scompenso cardiaco e il battito irregolare.', ko: '심부전과 부정맥을 치료합니다.', th: 'รักษาภาวะหัวใจล้มเหลวและหัวใจเต้นผิดจังหวะ', vi: 'Điều trị suy tim và nhịp tim không đều.', id: 'Mengobati gagal jantung dan detak jantung tidak teratur.', tr: 'Kalp yetmezliğini ve düzensiz kalp atışını tedavi eder.', ru: 'Лечит сердечную недостаточность и аритмию.', ar: 'يعالج قصور القلب وعدم انتظام ضربات القلب.', hi: 'हृदय विफलता और अनियमित दिल की धड़कन का उपचार करता है।' },
  'Relieves wheezing and shortness of breath.': {
    ja: 'ぜん鳴(ヒューヒュー)と息切れを和らげます。', zh: '缓解喘息和呼吸急促。', es: 'Alivia las sibilancias y la falta de aire.', fr: 'Soulage la respiration sifflante et l’essoufflement.', de: 'Lindert Keuchen und Atemnot.', pt: 'Alivia chiado e falta de ar.', it: 'Allevia il respiro sibilante e la mancanza di fiato.', ko: '천명(쌕쌕거림)과 숨 가쁨을 완화합니다.', th: 'บรรเทาอาการหายใจมีเสียงหวีดและหายใจไม่สะดวก', vi: 'Giảm khò khè và khó thở.', id: 'Meredakan mengi dan sesak napas.', tr: 'Hırıltıyı ve nefes darlığını giderir.', ru: 'Снимает свистящее дыхание и одышку.', ar: 'يخفف الأزيز وضيق التنفس.', hi: 'घरघराहट और सांस की तकलीफ से राहत देता है।' },
  'Reduces airway inflammation in asthma.': {
    ja: '喘息の気道の炎症を抑えます。', zh: '减轻哮喘中的气道炎症。', es: 'Reduce la inflamación de las vías respiratorias en el asma.', fr: 'Réduit l’inflammation des voies respiratoires dans l’asthme.', de: 'Reduziert Atemwegsentzündungen bei Asthma.', pt: 'Reduz a inflamação das vias aéreas na asma.', it: 'Riduce l’infiammazione delle vie aeree nell’asma.', ko: '천식의 기도 염증을 줄입니다.', th: 'ลดการอักเสบของทางเดินหายใจในโรคหอบหืด', vi: 'Giảm viêm đường thở trong hen suyễn.', id: 'Mengurangi peradangan saluran napas pada asma.', tr: 'Astımda hava yolu iltihabını azaltır.', ru: 'Снижает воспаление дыхательных путей при астме.', ar: 'يقلل التهاب مجرى الهواء في الربو.', hi: 'अस्थमा में वायुमार्ग की सूजन कम करता है।' },
  'Prevents asthma symptoms and allergies.': {
    ja: '喘息症状とアレルギーを予防します。', zh: '预防哮喘症状和过敏。', es: 'Previene los síntomas del asma y las alergias.', fr: 'Prévient les symptômes de l’asthme et les allergies.', de: 'Beugt Asthmasymptomen und Allergien vor.', pt: 'Previne sintomas de asma e alergias.', it: 'Previene i sintomi dell’asma e le allergie.', ko: '천식 증상과 알레르기를 예방합니다.', th: 'ป้องกันอาการหอบหืดและอาการแพ้', vi: 'Ngăn ngừa triệu chứng hen suyễn và dị ứng.', id: 'Mencegah gejala asma dan alergi.', tr: 'Astım belirtilerini ve alerjileri önler.', ru: 'Предотвращает симптомы астмы и аллергии.', ar: 'يمنع أعراض الربو والحساسية.', hi: 'अस्थमा के लक्षण और एलर्जी रोकता है।' },
  'Relieves breathing difficulty in COPD.': {
    ja: 'COPD(慢性閉塞性肺疾患)の呼吸困難を和らげます。', zh: '缓解慢阻肺中的呼吸困难。', es: 'Alivia la dificultad para respirar en la EPOC.', fr: 'Soulage les difficultés respiratoires dans la BPCO.', de: 'Lindert Atembeschwerden bei COPD.', pt: 'Alivia a dificuldade de respirar na DPOC.', it: 'Allevia la difficoltà respiratoria nella BPCO.', ko: 'COPD(만성폐쇄성폐질환)의 호흡곤란을 완화합니다.', th: 'บรรเทาอาการหายใจลำบากในโรคปอดอุดกั้นเรื้อรัง', vi: 'Giảm khó thở trong COPD.', id: 'Meredakan kesulitan bernapas pada PPOK.', tr: 'KOAH’ta nefes alma zorluğunu giderir.', ru: 'Снимает затруднённое дыхание при ХОБЛ.', ar: 'يخفف صعوبة التنفس في مرض الانسداد الرئوي المزمن.', hi: 'सीओपीडी में सांस लेने में कठिनाई से राहत देता है।' },
  'Prevents asthma and COPD symptoms.': {
    ja: '喘息とCOPDの症状を予防します。', zh: '预防哮喘和慢阻肺症状。', es: 'Previene los síntomas del asma y la EPOC.', fr: 'Prévient les symptômes de l’asthme et de la BPCO.', de: 'Beugt Symptomen von Asthma und COPD vor.', pt: 'Previne sintomas de asma e DPOC.', it: 'Previene i sintomi di asma e BPCO.', ko: '천식과 COPD의 증상을 예방합니다.', th: 'ป้องกันอาการหอบหืดและปอดอุดกั้นเรื้อรัง', vi: 'Ngăn ngừa triệu chứng hen suyễn và COPD.', id: 'Mencegah gejala asma dan PPOK.', tr: 'Astım ve KOAH belirtilerini önler.', ru: 'Предотвращает симптомы астмы и ХОБЛ.', ar: 'يمنع أعراض الربو ومرض الانسداد الرئوي المزمن.', hi: 'अस्थमा और सीओपीडी के लक्षण रोकता है।' },
  'Treats depression and anxiety.': {
    ja: 'うつ病と不安を治療します。', zh: '治疗抑郁和焦虑。', es: 'Trata la depresión y la ansiedad.', fr: 'Traite la dépression et l’anxiété.', de: 'Behandelt Depressionen und Angst.', pt: 'Trata depressão e ansiedade.', it: 'Tratta depressione e ansia.', ko: '우울증과 불안을 치료합니다.', th: 'รักษาภาวะซึมเศร้าและวิตกกังวล', vi: 'Điều trị trầm cảm và lo âu.', id: 'Mengobati depresi dan kecemasan.', tr: 'Depresyonu ve kaygıyı tedavi eder.', ru: 'Лечит депрессию и тревогу.', ar: 'يعالج الاكتئاب والقلق.', hi: 'अवसाद और चिंता का उपचार करता है।' },
  'Treats depression, anxiety, and nerve pain.': {
    ja: 'うつ病・不安・神経痛を治療します。', zh: '治疗抑郁、焦虑和神经痛。', es: 'Trata la depresión, la ansiedad y el dolor nervioso.', fr: 'Traite la dépression, l’anxiété et la douleur nerveuse.', de: 'Behandelt Depressionen, Angst und Nervenschmerzen.', pt: 'Trata depressão, ansiedade e dor neuropática.', it: 'Tratta depressione, ansia e dolore neuropatico.', ko: '우울증·불안·신경통을 치료합니다.', th: 'รักษาภาวะซึมเศร้า วิตกกังวล และปวดเส้นประสาท', vi: 'Điều trị trầm cảm, lo âu và đau thần kinh.', id: 'Mengobati depresi, kecemasan, dan nyeri saraf.', tr: 'Depresyonu, kaygıyı ve sinir ağrısını tedavi eder.', ru: 'Лечит депрессию, тревогу и невралгию.', ar: 'يعالج الاكتئاب والقلق وألم الأعصاب.', hi: 'अवसाद, चिंता और तंत्रिका दर्द का उपचार करता है।' },
  'Treats nerve pain, migraine, and depression.': {
    ja: '神経痛・片頭痛・うつ病を治療します。', zh: '治疗神经痛、偏头痛和抑郁。', es: 'Trata el dolor nervioso, la migraña y la depresión.', fr: 'Traite la douleur nerveuse, la migraine et la dépression.', de: 'Behandelt Nervenschmerzen, Migräne und Depressionen.', pt: 'Trata dor neuropática, enxaqueca e depressão.', it: 'Tratta dolore neuropatico, emicrania e depressione.', ko: '신경통·편두통·우울증을 치료합니다.', th: 'รักษาอาการปวดเส้นประสาท ไมเกรน และภาวะซึมเศร้า', vi: 'Điều trị đau thần kinh, đau nửa đầu và trầm cảm.', id: 'Mengobati nyeri saraf, migrain, dan depresi.', tr: 'Sinir ağrısını, migreni ve depresyonu tedavi eder.', ru: 'Лечит невралгию, мигрень и депрессию.', ar: 'يعالج ألم الأعصاب والصداع النصفي والاكتئاب.', hi: 'तंत्रिका दर्द, माइग्रेन और अवसाद का उपचार करता है।' },
  'Treats nerve pain and seizures.': {
    ja: '神経痛と発作を治療します。', zh: '治疗神经痛和癫痫发作。', es: 'Trata el dolor nervioso y las convulsiones.', fr: 'Traite la douleur nerveuse et les convulsions.', de: 'Behandelt Nervenschmerzen und Krampfanfälle.', pt: 'Trata dor neuropática e convulsões.', it: 'Tratta dolore neuropatico e crisi convulsive.', ko: '신경통과 발작을 치료합니다.', th: 'รักษาอาการปวดเส้นประสาทและอาการชัก', vi: 'Điều trị đau thần kinh và co giật.', id: 'Mengobati nyeri saraf dan kejang.', tr: 'Sinir ağrısını ve nöbetleri tedavi eder.', ru: 'Лечит невралгию и судороги.', ar: 'يعالج ألم الأعصاب والنوبات.', hi: 'तंत्रिका दर्द और दौरे का उपचार करता है।' },
  'Treats nerve pain and anxiety.': {
    ja: '神経痛と不安を治療します。', zh: '治疗神经痛和焦虑。', es: 'Trata el dolor nervioso y la ansiedad.', fr: 'Traite la douleur nerveuse et l’anxiété.', de: 'Behandelt Nervenschmerzen und Angst.', pt: 'Trata dor neuropática e ansiedade.', it: 'Tratta dolore neuropatico e ansia.', ko: '신경통과 불안을 치료합니다.', th: 'รักษาอาการปวดเส้นประสาทและวิตกกังวล', vi: 'Điều trị đau thần kinh và lo âu.', id: 'Mengobati nyeri saraf dan kecemasan.', tr: 'Sinir ağrısını ve kaygıyı tedavi eder.', ru: 'Лечит невралгию и тревогу.', ar: 'يعالج ألم الأعصاب والقلق.', hi: 'तंत्रिका दर्द और चिंता का उपचार करता है।' },
  'Prevents migraines and treats seizures.': {
    ja: '片頭痛を予防し、発作を治療します。', zh: '预防偏头痛并治疗癫痫发作。', es: 'Previene las migrañas y trata las convulsiones.', fr: 'Prévient les migraines et traite les convulsions.', de: 'Beugt Migräne vor und behandelt Krampfanfälle.', pt: 'Previne enxaquecas e trata convulsões.', it: 'Previene le emicranie e tratta le crisi convulsive.', ko: '편두통을 예방하고 발작을 치료합니다.', th: 'ป้องกันไมเกรนและรักษาอาการชัก', vi: 'Ngăn ngừa đau nửa đầu và điều trị co giật.', id: 'Mencegah migrain dan mengobati kejang.', tr: 'Migreni önler ve nöbetleri tedavi eder.', ru: 'Предотвращает мигрень и лечит судороги.', ar: 'يمنع الصداع النصفي ويعالج النوبات.', hi: 'माइग्रेन रोकता है और दौरे का उपचार करता है।' },
  'Relieves migraine attacks.': {
    ja: '片頭痛発作を和らげます。', zh: '缓解偏头痛发作。', es: 'Alivia los ataques de migraña.', fr: 'Soulage les crises de migraine.', de: 'Lindert Migräneanfälle.', pt: 'Alivia crises de enxaqueca.', it: 'Allevia gli attacchi di emicrania.', ko: '편두통 발작을 완화합니다.', th: 'บรรเทาอาการไมเกรน', vi: 'Giảm cơn đau nửa đầu.', id: 'Meredakan serangan migrain.', tr: 'Migren ataklarını giderir.', ru: 'Снимает приступы мигрени.', ar: 'يخفف نوبات الصداع النصفي.', hi: 'माइग्रेन के दौरे से राहत देता है।' },
  'Relieves Parkinson’s symptoms.': {
    ja: 'パーキンソン病の症状を和らげます。', zh: '缓解帕金森病症状。', es: 'Alivia los síntomas del párkinson.', fr: 'Soulage les symptômes de la maladie de Parkinson.', de: 'Lindert Parkinson-Symptome.', pt: 'Alivia os sintomas de Parkinson.', it: 'Allevia i sintomi del Parkinson.', ko: '파킨슨병 증상을 완화합니다.', th: 'บรรเทาอาการพาร์กินสัน', vi: 'Giảm triệu chứng Parkinson.', id: 'Meredakan gejala Parkinson.', tr: 'Parkinson belirtilerini giderir.', ru: 'Снимает симптомы болезни Паркинсона.', ar: 'يخفف أعراض باركنسون.', hi: 'पार्किंसंस के लक्षणों से राहत देता है।' },
  'Treats ADHD.': {
    ja: 'ADHDを治療します。', zh: '治疗ADHD（注意缺陷多动障碍）。', es: 'Trata el TDAH.', fr: 'Traite le TDAH.', de: 'Behandelt ADHS.', pt: 'Trata o TDAH.', it: 'Tratta l’ADHD.', ko: 'ADHD를 치료합니다.', th: 'รักษาโรคสมาธิสั้น', vi: 'Điều trị ADHD.', id: 'Mengobati ADHD.', tr: 'DEHB’yi tedavi eder.', ru: 'Лечит СДВГ.', ar: 'يعالج فرط الحركة ونقص الانتباه.', hi: 'एडीएचडी का उपचार करता है।' },
  'Relieves anxiety (short-term).': {
    ja: '不安を(短期的に)和らげます。', zh: '（短期）缓解焦虑。', es: 'Alivia la ansiedad (a corto plazo).', fr: 'Soulage l’anxiété (à court terme).', de: 'Lindert Angst (kurzzeitig).', pt: 'Alivia a ansiedade (curto prazo).', it: 'Allevia l’ansia (a breve termine).', ko: '불안을 (단기적으로) 완화합니다.', th: 'บรรเทาอาการวิตกกังวล (ระยะสั้น)', vi: 'Giảm lo âu (ngắn hạn).', id: 'Meredakan kecemasan (jangka pendek).', tr: 'Kaygıyı (kısa süreli) giderir.', ru: 'Снимает тревогу (кратковременно).', ar: 'يخفف القلق (على المدى القصير).', hi: 'चिंता से (अल्पकालिक) राहत देता है।' },
  'Helps with insomnia.': {
    ja: '不眠を改善します。', zh: '帮助改善失眠。', es: 'Ayuda con el insomnio.', fr: 'Aide contre l’insomnie.', de: 'Hilft bei Schlaflosigkeit.', pt: 'Ajuda com insônia.', it: 'Aiuta contro l’insonnia.', ko: '불면증을 돕습니다.', th: 'ช่วยเรื่องนอนไม่หลับ', vi: 'Giúp cải thiện chứng mất ngủ.', id: 'Membantu mengatasi insomnia.', tr: 'Uykusuzluğa yardımcı olur.', ru: 'Помогает при бессоннице.', ar: 'يساعد في علاج الأرق.', hi: 'अनिद्रा में मदद करता है।' },
  'Helps regulate sleep.': {
    ja: '睡眠のリズムを整えます。', zh: '帮助调节睡眠。', es: 'Ayuda a regular el sueño.', fr: 'Aide à réguler le sommeil.', de: 'Hilft, den Schlaf zu regulieren.', pt: 'Ajuda a regular o sono.', it: 'Aiuta a regolare il sonno.', ko: '수면 리듬을 조절합니다.', th: 'ช่วยปรับการนอนหลับ', vi: 'Giúp điều hòa giấc ngủ.', id: 'Membantu mengatur tidur.', tr: 'Uykuyu düzenlemeye yardımcı olur.', ru: 'Помогает регулировать сон.', ar: 'يساعد على تنظيم النوم.', hi: 'नींद को नियंत्रित करने में मदद करता है।' },
  'Treats bacterial infections.': {
    ja: '細菌感染症を治療します。', zh: '治疗细菌感染。', es: 'Trata las infecciones bacterianas.', fr: 'Traite les infections bactériennes.', de: 'Behandelt bakterielle Infektionen.', pt: 'Trata infecções bacterianas.', it: 'Tratta le infezioni batteriche.', ko: '세균 감염을 치료합니다.', th: 'รักษาการติดเชื้อแบคทีเรีย', vi: 'Điều trị nhiễm khuẩn.', id: 'Mengobati infeksi bakteri.', tr: 'Bakteriyel enfeksiyonları tedavi eder.', ru: 'Лечит бактериальные инфекции.', ar: 'يعالج الالتهابات البكتيرية.', hi: 'जीवाणु संक्रमण का उपचार करता है।' },
  'Treats fungal infections.': {
    ja: '真菌感染症を治療します。', zh: '治疗真菌感染。', es: 'Trata las infecciones fúngicas.', fr: 'Traite les infections fongiques.', de: 'Behandelt Pilzinfektionen.', pt: 'Trata infecções fúngicas.', it: 'Tratta le infezioni fungine.', ko: '진균 감염을 치료합니다.', th: 'รักษาการติดเชื้อรา', vi: 'Điều trị nhiễm nấm.', id: 'Mengobati infeksi jamur.', tr: 'Mantar enfeksiyonlarını tedavi eder.', ru: 'Лечит грибковые инфекции.', ar: 'يعالج الالتهابات الفطرية.', hi: 'फंगल संक्रमण का उपचार करता है।' },
  'Treats herpes infections.': {
    ja: 'ヘルペス感染症を治療します。', zh: '治疗疱疹感染。', es: 'Trata las infecciones por herpes.', fr: 'Traite les infections à herpès.', de: 'Behandelt Herpes-Infektionen.', pt: 'Trata infecções por herpes.', it: 'Tratta le infezioni da herpes.', ko: '헤르페스 감염을 치료합니다.', th: 'รักษาการติดเชื้อเริม', vi: 'Điều trị nhiễm herpes.', id: 'Mengobati infeksi herpes.', tr: 'Herpes enfeksiyonlarını tedavi eder.', ru: 'Лечит герпетические инфекции.', ar: 'يعالج عدوى الهربس.', hi: 'हर्पीज संक्रमण का उपचार करता है।' },
  'Treats influenza.': {
    ja: 'インフルエンザを治療します。', zh: '治疗流感。', es: 'Trata la gripe.', fr: 'Traite la grippe.', de: 'Behandelt Grippe.', pt: 'Trata a gripe.', it: 'Tratta l’influenza.', ko: '인플루엔자를 치료합니다.', th: 'รักษาโรคไข้หวัดใหญ่', vi: 'Điều trị cúm.', id: 'Mengobati influenza.', tr: 'Gribi tedavi eder.', ru: 'Лечит грипп.', ar: 'يعالج الإنفلونزا.', hi: 'इन्फ्लूएंजा का उपचार करता है।' },
  'Relieves allergy symptoms.': {
    ja: 'アレルギー症状を和らげます。', zh: '缓解过敏症状。', es: 'Alivia los síntomas de alergia.', fr: 'Soulage les symptômes d’allergie.', de: 'Lindert Allergiesymptome.', pt: 'Alivia os sintomas de alergia.', it: 'Allevia i sintomi allergici.', ko: '알레르기 증상을 완화합니다.', th: 'บรรเทาอาการแพ้', vi: 'Giảm triệu chứng dị ứng.', id: 'Meredakan gejala alergi.', tr: 'Alerji belirtilerini giderir.', ru: 'Снимает симптомы аллергии.', ar: 'يخفف أعراض الحساسية.', hi: 'एलर्जी के लक्षणों से राहत देता है।' },
  'Relieves allergies and helps sleep.': {
    ja: 'アレルギーを和らげ、眠りを助けます。', zh: '缓解过敏并帮助睡眠。', es: 'Alivia las alergias y ayuda a dormir.', fr: 'Soulage les allergies et aide au sommeil.', de: 'Lindert Allergien und hilft beim Schlafen.', pt: 'Alivia alergias e ajuda a dormir.', it: 'Allevia le allergie e aiuta a dormire.', ko: '알레르기를 완화하고 수면을 돕습니다.', th: 'บรรเทาอาการแพ้และช่วยให้นอนหลับ', vi: 'Giảm dị ứng và hỗ trợ giấc ngủ.', id: 'Meredakan alergi dan membantu tidur.', tr: 'Alerjileri giderir ve uyumaya yardımcı olur.', ru: 'Снимает аллергию и помогает заснуть.', ar: 'يخفف الحساسية ويساعد على النوم.', hi: 'एलर्जी से राहत देता है और नींद में मदद करता है।' },
}
